### ISSUE TITLE
How to register SLES Systems using Autoyast XML

### ISSUE THREAD

**Issue by heiwu** [SUSE/manager-build-profiles#24]
in https://github.com/SUSE/manager-build-profiles/blob/master/AutoYaST/SLES-15-SP2-installation/README.md it says "For using an activation key, specify the following valiable: registration_key=...."

I can't find any reference to "registration_key" in both .xml files within https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST/SLES-15-SP2-installation. Is that a bug / missing implementation? Or any kind of integrated default behavior?
How can i register newly installed systems using autoyast?

**Comment by admd** [comment]
hey @heiwu , these variables are part of [minion_script](https://github.com/SUSE/manager-build-profiles/blob/master/AutoYaST/SLES-15-SP2-installation/sles15-sp2-autoyast.xml#L120) snippet. Complete snippet contents you can see [here](https://github.com/uyuni-project/uyuni/blob/master/java/conf/cobbler/snippets/minion_script) .

You can set these variables from the suse manager UI as well.

**Comment by heiwu** [comment]
I somehow thought there would be any option to register directly from autoyast. A bootstrap script defined in <scripts> is our current "way to go", too. So seems like we are fine.
Thanks for replying, @admd
