### ISSUE TITLE
Ignition Firstboot issue

### ISSUE THREAD

**Issue by slsnow** [SUSE/manager-build-profiles#42]
`\$ignition_firstboot`

There are several entries like this in  `OSImage/SLE-Micro54/SLE-Micro.kiwi`. 

We're a bit confused by these, if that's just a typo or something. I'm not sure what the `\$` is for. It seems like it should be `ignition.firstboot`

Let me know what you think, thanks.

**Comment by crisman** [comment]
Not an issue.

The `\$ignition_firstboot` is escaping a shell variable that is used in `grub.cfg` as "$ignition_firstboot".
https://www.gnu.org/software/grub/manual/grub/html_node/Shell_002dlike-scripting.html

For upstream see:
https://github.com/coreos/ignition/blob/main/grub2/ignition.cfg

Which sometimes sets `$ignition_firstboot`  to be a string starting with `ignition.firstboot `.

In SLE Micro the grub.d file has a bit different contents, but uses the same variable. See `rpm -ql ignition-dracut-grub2` for details in the file under `/etc/grub.d`.

**Comment by slsnow** [comment]
Thanks, Daniel, for the explanation.
